stages:
  - build
  - test

build:
  stage: build
  image: gcc:latest
  script:
    - apt-get update && apt-get install -y build-essential git cmake
    - apt-get install -y libasound2-dev mesa-common-dev libx11-dev libxrandr-dev libxi-dev xorg-dev libgl1-mesa-dev libglu1-mesa-dev
    - git clone https://github.com/raysan5/raylib.git raylib
    - cd raylib
    - mkdir build && cd build
    - cmake -DBUILD_SHARED_LIBS=ON ..
    - make
    - sudo make install
    - cd ../..
    - git clone https://github.com/raysan5/raygui raygui
    - cd raygui
    - mv src/raygui.h src/raygui.c
    - gcc -o raygui.so src/raygui.c -shared -fpic -DRAYGUI_IMPLEMENTATION -lraylib -lGL -lm -lpthread -ldl -lrt -lX11
    - cd ..
    - cc main.c `pkg-config --libs --cflags raylib` -o app
  artifacts:
    paths:
      - app

test:
  stage: test
  image: gcc:latest
  script:
    - cc test.c -o bin/test
    - ./bin/test
